server:
  port: 81

spring:
  application:
    name: cloud-consumer-order80

eureka:
  client:
    service-url:
      defaultZone: http://www.eureka7001.com:7001/eureka/,http://www.eureka7002.com:7002/eureka/ #集群版
    register-with-eureka: true
    fetch-registry: true
