server:
  port: 81

spring:
  application:
    # 服务别名
    name: cloud-consumer-order
  cloud:
    consul:
      # consul注册中心地址
      host: 192.168.198.128
      port: 8500
      discovery:
        hostname: 127.0.0.1
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true



