server:
  port: 3344

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/samsarawsf/springcloud-config.git
          search-paths:
            - springcloud-config
          force-pull: true
          username: samsarawsf
          password: Wsf200068.
      label: main

  rabbitmq:
    host: 192.168.198.128
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'
