server:
  # 8004表示注册到zookeeper服务器的支付服务提供者端口号
  port: 8004
spring:
  application:
    # 服务别名---注册zookeeper到注册中心的名称
    name: cloud-provider-payment
  cloud:
    zookeeper:
      # 默认192.168.198.128:2181
      connect-string: 192.168.198.128:2181
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      #开启缓存
    cache-enabled: true
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.wsf.springcloud.pojo


